debug: false
# Should we scrape VM stats?
vmstats: true
# Should we scrape VM Perf counters?
vmperfcounters: true

# List of vmware targets
hosts:
  - host: vcenter1.vmware.lan
    user: username
    password: mypass
  - host: vcenter2.vmware.lan
    user: username
    password: mypass

